### ISSUE TITLE
Parsing error on linear expression with varying token order

### ISSUE THREAD

**Issue by byronwall** [dsharlet/ComputerAlgebra#1]
I am evaluating this library for some symbolic work but having an issue with expression parsing.  The expression `C2+22*D2` throws an error `Expected end` whereas the expression `C2+D2*22` is correctly parsed.  While stepping through, it appears that in the former case, the `+22` is being parsed as a single token whereas in the latter case, the `+` and `D2` are parsed as individual tokens.

Is this intended to be a limitation of the parser (i.e. variables must precede constants) or I am bumping up against a bug?

For what it's worth, if I construct my expressions to avoid this issue, this library appears quite promising for what I am trying to do: build a tree of all expressions in an Excel spreadsheet.  The `Arrow` syntax is quite nice for being able to hold the constants while using an `Expression` for formulas and evaluating them all at once at the end.  I'd love to push this out into a full solution if I can get around this parsing error.

I can provide a full stack trace or other diagnostics if needed, but I assume this is relatively simple to reproduce without a trace.

```C#
string formula = "C2+22*D2";
ComputerAlgebra.Expression thisCell = formula; // this line throws the error
```

**Comment by dsharlet** [comment]
It was a bug, should be fixed now. Thanks for reporting the issue.

**Comment by byronwall** [comment]
Works well now.  Thanks for the quick response.

**Comment by dsharlet** [comment]
BTW, I was curious how it could be possible that I haven't hit this bug until now, so I was digging around. My convention is to use spaces around + and -, which accidentally works around this issue. So, "C2 + 22*D2" would have worked :)

Still, glad to have fixed this.
